"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { supabase } from "@/lib/supabase";
import { ListingCard } from "@/components/listing-card";
type Listing={id:string;title:string|null;description:string|null;listing_type:string|null;market_category:string|null;market_subcategories:string[]|null;city:string|null;city_name:string|null;state_name:string|null;image_url:string|null;image_urls:string[]|null;price_label:string|null;price_per_hour:number|null;price_per_day:number|null;capacity:number|null;verified_host:boolean|null};
const categories=["Espaços","Mesas e cadeiras","Brinquedos","Tendas e estruturas","Equipamentos"];
export default function Explorar(){const params=useSearchParams();const [items,setItems]=useState<Listing[]>([]);const [q,setQ]=useState(params.get("q")||"");const [city,setCity]=useState(params.get("cidade")||"");const [category,setCategory]=useState("");const [loading,setLoading]=useState(true);
useEffect(()=>{supabase.from("marketplace_listings").select("id,title,description,listing_type,market_category,market_subcategories,city,city_name,state_name,image_url,image_urls,price_label,price_per_hour,price_per_day,capacity,verified_host").order("title").then(({data})=>{setItems((data||[]) as Listing[]);setLoading(false)})},[]);
const filtered=useMemo(()=>items.filter(item=>{const text=[item.title,item.description,item.city,item.city_name,item.market_category,...(item.market_subcategories||[])].filter(Boolean).join(" ").toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(!city||[item.city,item.city_name].filter(Boolean).join(" ").toLowerCase().includes(city.toLowerCase()))&&(!category||(item.market_category||"").toLowerCase().includes(category.toLowerCase()))}),[items,q,city,category]);
return <main className="page"><section className="page-heading"><span className="eyebrow">Catálogo</span><h1>Encontre tudo para organizar seu evento.</h1><p className="muted">Espaços, equipamentos e itens para festa. Negocie direto com quem anuncia.</p></section><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="O que você precisa?"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Onde?"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="category-row"><Link href="/explorar">Tudo</Link>{categories.map(x=><button key={x} onClick={()=>setCategory(x)}>{x}</button>)}</div>{loading?<div className="empty">Carregando anúncios...</div>:filtered.length===0?<div className="empty">Nenhum anúncio encontrado.</div>:<div className="listing-grid">{filtered.map(item=><ListingCard key={item.id} listing={item}/>)}</div>}</main>}
